# Generated by Django 5.1.3 on 2024-11-05 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_prompt', models.TextField(help_text='Treść zadania do wykonania przez agenta')),
                ('task_output', models.TextField(blank=True, help_text='Wynik zwrócony przez agenta', null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Data utworzenia zadania')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Data ostatniej aktualizacji')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Data uruchomienia')),
                ('execution_time', models.FloatField(blank=True, help_text='Czas wykonania w sekundach', null=True)),
                ('task', models.ForeignKey(help_text='Powiązane zadanie', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.task')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
